name: Build Chopin Upgrade Artifact
description: Install Nix and build the Chopin upgrade artifact.

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v27

    - name: Build chopin upgrade artifact
      shell: bash
      run: ./scripts/build-chopin-upgrade-artifact.sh
