name: Nix CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Check Nix formatting
        run: nix run ./nix#formatter.x86_64-linux -- --check .

      - name: Evaluate flake checks (no build)
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: nix flake check ./nix --no-build --show-trace --impure
